src/app.py
from flask import Flask, render_template
from src.common.database import Database

app = Flask(__name__)
app.config.from_object('src.config')
app.secret_key = '123'

@app.before_first_request
def init_db():
    Database.initialize()

@app.route("/")
def home():
    return render_template('home.html')

from src.models.users.views import user_blueprint
from src.models.stores.views import store_blueprint
from src.models.alerts.views import alert_blueprint
app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for

from src.models.alerts.alert import Alert
from src.models.items.item import Item

alert_blueprint = Blueprint('alerts', __name__)

#Alert Index page
@alert_blueprint.route('/')
def index():
    return "This is alert page"

#Create alert page
@alert_blueprint.route('/new', methods=['POST','GET'])
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price'])
        item = Item(name, url)
        item.save_to_mongo()
        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()

    return render_template('alerts/create_alert.html')

#Edit alert page
@alert_blueprint.route('/edit/<string:alert_id>', methods=['POST', 'GET'])
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)

    if request.method == 'POST':

        price_limit = float(request.form['price'])
        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alert'))

    return render_template('alerts/edit_alert.html', alert=alert)


#Deactive an activated alert
@alert_blueprint.route('/deactivate/<string:alert_id>')
def deactive_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alert'))

#Active an deactivated alert
@alert_blueprint.route('/activate/<string:alert_id>')
def active_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alert'))

#Delete an deactivated alert
@alert_blueprint.route('/delete/<string:alert_id>')
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alert'))


#Display alert detail page
@alert_blueprint.route('/<string:alert_id>')
def alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('/alerts/alert.html', alert=alert)

#Refresh Price
@alert_blueprint.route('/check_price/<string:alert_id>')
def check_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.alert_page', alert_id=alert_id))


#Check alert for specified user
@alert_blueprint.route('/for_user/<string:user_id>')
def get_alerts_for_user(user_id):
    pass

src/models/items/views.py
from flask import Blueprint



item_blueprint = Blueprint('items', __name__)


#Item page
@item_blueprint.route('/item/<string:name>')
def item_page():
    pass

src/models/stores/views.py
from flask import Blueprint, render_template, redirect, url_for, request,json

from src.models.stores.store import Store

store_blueprint = Blueprint('stores', __name__)

#Store Index
@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('/stores/store_index.html', stores=stores)

#Store page
@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    store = Store.get_by_id(store_id)
    return render_template('stores/store.html', store=store)

#Create Store
@store_blueprint.route('/new', methods=['POST', 'GET'])
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('/stores/create_store.html')

#Edit Store
@store_blueprint.route('/edit/<string:store_id>', methods=['POST','GET'])
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == 'POST':
        if request.method == 'POST':
            name = request.form['name']
            url_prefix = request.form['url_prefix']
            tag_name = request.form['tag_name']
            query = request.form['query']

            store.name = name
            store.url_prefix = url_prefix
            store.tag_name = tag_name
            store.query = query

            store.save_to_mongo()

            return redirect(url_for('.index'))

    return render_template('/stores/edit_store.html', store=store)

#Delete Store
@store_blueprint.route('/delete/<string:store_id>')
def delete_store(store_id):
    store=Store.get_by_id(store_id)
    store.delete()
    return redirect(url_for('.index'))

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
import src.models.users.error as UserError
from src.models.users.user import User

user_blueprint = Blueprint('users', __name__)


#Login Page
@user_blueprint.route('/login', methods=['POST', 'GET'])
def user_login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alert"))
        except UserError.UserError as e:
            return e.message

    return render_template('/users/login.html')




#Register Page
@user_blueprint.route('/register', methods=['POST', 'GET'])
def user_register():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alert"))

        except UserError.UserError as e:
            return e.message

    return render_template('/users/register.html')


#Alert Page
@user_blueprint.route('/alert')
def user_alert():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template('/users/alerts.html', alerts=alerts)



#Logout Page
@user_blueprint.route('/logout')
def user_logout():
    session['email'] = None
    return redirect(url_for('home'))


#Check alerts by specified user
@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h1>Alert Information for {{ alert.item.name }}</h1>
    <p>Last checked time <strong>{{ alert.last_checked.strftime('%d-%m-%Y at %H:%M')}}</strong</p>
    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-default" target="_blank" href="{{ alert.item.url }}" role="button">Visit Site</a>
            <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit Alert</a>
            {% if alert.active %}
            <a class="btn btn-danger" href="{{ url_for('alerts.deactive_alert', alert_id=alert._id) }}"
               role="button">Deactive Alert</a>
            {% else %}
            <a class="btn btn-success" href="{{ url_for('alerts.active_alert', alert_id=alert._id) }}"
               role="button">Active Alert</a>
            <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}"
               role="button">Delete Alert</a>
            {% endif %}
            <a class="btn btn-warning" href="{{ url_for('alerts.check_price', alert_id=alert._id) }}" role="button">Check
                Price</a>
        </div>
    </div>
</div>
{% endblock %}

src/templates/alerts/create_alert.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h1>Create Alert</h1>
</div>
<div class="form-style">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert/Item Name</label>
            <input type="text" name="name" id="name" placeholder="name" class="form-control">
        </div>
        <div class="form-group">
            <label for="name">URL</label>
            <input type="text" name="url" id="url" placeholder="http://..." class="form-control">
        </div>
        <div class="form-group">
            <label for="price">Price Limit</label>
            <input type="text" name="price" id="price" placeholder="50.0" class="form-control" aria-describedby="priceLimitBlock">
            <p id="priceLimitBlock" class="help-block">We'll send you an email when the price reaches or goes under this.</p>
        </div>
        <button class="btn btn-success" type="submit">Create New</button>
    </form>
</div>
{% endblock %}

src/templates/alerts/edit_alert.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h1>Edit Alert</h1>
</div>
<div class="form-style">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert/Item Name</label>
            <input type="text" name="name" id="name" placeholder="name" class="form-control" disabled>
        </div>
        <div class="form-group">
            <label for="name">URL</label>
            <input type="text" name="url" id="url" placeholder="http://..." class="form-control" disabled>
        </div>
        <div class="form-group">
            <label for="price">Price Limit</label>
            <input type="text" name="price" id="price" value="{{ alert.price_limit }}" placeholder="50.0" class="form-control" aria-describedby="priceLimitBlock">
            <p id="priceLimitBlock" class="help-block">We'll send you an email when the price reaches or goes under this.</p>
        </div>
        <button class="btn btn-success" type="submit">Edit Alert</button>
    </form>
</div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Alert My Wishlist</title>

    {% include 'html_dependencies.html' %}
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"><span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Alert My Wishlist</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('stores.index') }}">Stores</a></li>
            </ul>
            {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.user_alert') }}"><span class="glyphicon glyphicon-alert"></span> Your Alerts</a></li>
                    <li><a href="{{ url_for('users.user_logout') }}"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.user_register') }}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="{{ url_for('users.user_login') }}"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

src/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
    <h1>Alert Your Wish List</h1>
    <p>We can scan online store websites to notify you of price drops in your wish lists that interest you.</p>
    <p>Just sign up, and get started by adding the URL of an item that you wish to track. We'll do the rest!</p>
    <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.user_register') }}" role="button">Sign Up</a></p>
</div>
{% endblock %}

src/templates/html_dependencies.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

src/templates/stores/create_store.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h1>Create Store</h1>
</div>
<div class="form-style">
    <form method="post">
        <div class="form-group">
            <label for="name">Store Name</label>
            <input type="text" name="name" id="name" placeholder="Store Name" class="form-control">
        </div>
        <div class="form-group">
            <label for="url_prefix">Store URL Prefix</label>
            <input type="text" name="url_prefix" id="url_prefix" placeholder="http://..." class="form-control" aria-describedby="urlPrefixHelp">
             <span id="urlPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
        </div>
        <div class="form-group">
            <label for="tag_name">Tag Name</label>
            <input type="text" name="tag_name" id="tag_name" placeholder="span" class="form-control" aria-describedby="tagNameHelp">
            <span id="tagNameHelp" class="help-block">What's the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
        </div>
        <div class="form-group">
            <label for="query">Search Query</label>
            <input type="text" name="query" id="query" placeholder='{"class": "price"}' class="form-control" aria-describedby="queryHelp">
            <span id="queryHelp" class="help-block">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation marks!</span>
        </div>
        <button class="btn btn-success" type="submit">Create New</button>
    </form>
</div>
{% endblock %}

src/templates/stores/edit_store.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h1>Create Store</h1>
</div>
<div class="form-style">
    <form method="post">
        <div class="form-group">
            <label for="name">Store Name</label>
            <input type="text" name="name" id="name" placeholder="Store Name" value="{{ store.name }}" class="form-control">
        </div>
        <div class="form-group">
            <label for="url_prefix">Store URL Prefix</label>
            <input type="text" name="url_prefix" id="url_prefix" value="{{ store.url_prefix }}" placeholder="http://..." class="form-control" aria-describedby="urlPrefixHelp">
             <span id="urlPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
        </div>
        <div class="form-group">
            <label for="tag_name">Price Limit</label>
            <input type="text" name="tag_name" id="tag_name" placeholder="span" value="{{ store.tag_name }}" class="form-control" aria-describedby="tagNameHelp">
            <span id="tagNameHelp" class="help-block">What's the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
        </div>
        <div class="form-group">
            <label for="query">Search Query</label>
            <input type="text" name="query" id="query" placeholder='{"class":"price"}' value='{{ store.query }}' class="form-control" aria-describedby="queryHelp">
            <span id="queryHelp" class="help-block">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation marks!</span>
        </div>
        <button class="btn btn-warning" type="submit">Update Store</button>
    </form>
</div>
{% endblock %}

src/templates/stores/store.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h1>Store
        <small>{{ store.name }}</small>
    </h1>
</div>
<p>All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
<div class="panel panel-default">
    <div class="panel-body">
        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit
            Store</a>
        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Delete
            Store</a>
    </div>
</div>

{% endblock %}

src/templates/stores/store_index.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h1>Stores
        <small>list of supported stoers</small>
    </h1>
</div>
<div class="list-group">
    {% for stores in stores %}

        <a href="{{ url_for('stores.store_page', store_id=stores._id) }}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ stores.name }}</h4>
            <p class="list-group-item-text">All URLs in this store should start with <strong>{{ stores.url_prefix }}</strong></p>
        </a>
    {% endfor %}
</div>
<a class="btn btn-success" href="{{ url_for('stores.create_store') }}"><span class="glyphicon glyphicon-plus"></span> Create Store</a>
{% endblock %}

src/templates/users/alerts.html
{% extends 'base.html' %}
{% block content %}
<div class="page-header">
    <h1>Alerts
        <small>showing already existing alerts</small>
    </h1>
</div>
<div class="list-group">
    {% for alert in alerts %}
        <a href="{{ url_for('alerts.alert_page', alert_id=alert._id) }}" class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}">
            <h4 class="list-group-item-heading">
                <span class="{{ 'glyphicon glyphicon-remove-circle' if not alert.active else '' }}"></span> Alert for "{{ alert.item.name }}"</h4>
            <p class="list-group-item-text">Last price found <strong>{{ alert.item.price }}</strong><br/>
            Last checked time: <strong>{{ alert.last_checked.strftime('%d-%m-%Y at %H:%M')}}</strong></p>
        </a>
    {% endfor %}
</div>
<a class="btn btn-success" href="{{ url_for('alerts.create_alert') }}"><span class="glyphicon glyphicon-plus"></span> Create Alert</a>
{% endblock %}

src/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<div class="form-style">
    <form action="{{ url_for('users.user_login') }}" method="post">
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}

src/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<div class="form-style">
    <form action="{{ url_for('users.user_register') }}" method="post">
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}